import type { ModelProfile } from '../types/model.js';

// Minimum context floors:
// - 9B models: 8k (fast, small footprint)
// - 30-32B models: 16k (medium tasks)
// - 70B+ models: 32k (serious work needs serious context)
// - 100B+ models: 32k (never worth loading at less)
// - Embedding models: 2k (purpose-built)

export const MODEL_REGISTRY: Record<string, ModelProfile> = {
  'qwen3.5-9b-mlx': {
    id: 'qwen3.5-9b-mlx',
    name: 'Qwen 3.5 9B',
    capabilities: ['general', 'code', 'fast'],
    contextWindow: 32768,
    minContextLength: 8192,
    speed: 'fast',
    quality: 'low',
    supportsToolCalls: true,
    cost: 1,
  },
  'qwen3-32b-mlx': {
    id: 'qwen3-32b-mlx',
    name: 'Qwen 3 32B',
    capabilities: ['general', 'code', 'reasoning'],
    contextWindow: 32768,
    minContextLength: 16384,
    speed: 'medium',
    quality: 'medium',
    supportsToolCalls: true,
    cost: 3,
  },
  'gemma-4-31b-it@q8_0': {
    id: 'gemma-4-31b-it@q8_0',
    name: 'Gemma 4 31B (Q8)',
    capabilities: ['general', 'code', 'reasoning'],
    contextWindow: 32768,
    minContextLength: 16384,
    speed: 'medium',
    quality: 'medium',
    supportsToolCalls: true,
    cost: 3,
  },
  'qwen3.5-122b': {
    id: 'qwen3.5-122b',
    name: 'Qwen 3.5 122B',
    capabilities: ['general', 'code', 'reasoning'],
    contextWindow: 32768,
    minContextLength: 32768,
    speed: 'slow',
    quality: 'high',
    supportsToolCalls: true,
    cost: 7,
  },
  'qwen3.5-122b-a10b': {
    id: 'qwen3.5-122b-a10b',
    name: 'Qwen 3.5 122B MoE (10B active)',
    capabilities: ['general', 'code', 'reasoning', 'fast'],
    contextWindow: 32768,
    minContextLength: 32768,
    speed: 'fast',
    quality: 'medium',
    supportsToolCalls: true,
    cost: 2,
  },
  'llama-3.3-70b': {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    capabilities: ['general', 'code', 'reasoning'],
    contextWindow: 131072,
    minContextLength: 32768,
    speed: 'medium',
    quality: 'high',
    supportsToolCalls: true,
    cost: 5,
  },
  'qwen3-235b-thinking': {
    id: 'qwen3-235b-thinking',
    name: 'Qwen 3 235B Thinking',
    capabilities: ['reasoning', 'code'],
    contextWindow: 32768,
    minContextLength: 32768,
    speed: 'slow',
    quality: 'high',
    supportsToolCalls: false,
    cost: 10,
  },
  'qwen2.5-vl-72b': {
    id: 'qwen2.5-vl-72b',
    name: 'Qwen 2.5 VL 72B',
    capabilities: ['vision', 'general', 'code'],
    contextWindow: 32768,
    minContextLength: 32768,
    speed: 'slow',
    quality: 'high',
    supportsToolCalls: true,
    cost: 7,
  },
  'hermes-3-70b': {
    id: 'hermes-3-70b',
    name: 'Hermes 3 70B',
    capabilities: ['general', 'code', 'reasoning'],
    contextWindow: 131072,
    minContextLength: 32768,
    speed: 'medium',
    quality: 'high',
    supportsToolCalls: true,
    cost: 5,
  },
  'wizardlm-2-8x22b': {
    id: 'wizardlm-2-8x22b',
    name: 'WizardLM 2 8x22B',
    capabilities: ['general', 'code', 'reasoning'],
    contextWindow: 65536,
    minContextLength: 32768,
    speed: 'slow',
    quality: 'high',
    supportsToolCalls: true,
    cost: 8,
  },
  'text-embedding-nomic-embed-text-v1.5': {
    id: 'text-embedding-nomic-embed-text-v1.5',
    name: 'Nomic Embed Text v1.5',
    capabilities: ['embedding'],
    contextWindow: 8192,
    minContextLength: 2048,
    speed: 'fast',
    quality: 'medium',
    supportsToolCalls: false,
    cost: 1,
  },
};

export const DEFAULT_MODEL = 'qwen3.5-122b-a10b';
